name: API documentation
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Set up PHP (8.2)'
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - run: ./composer.phar install -n --no-progress -o
      - run: ./composer.phar api-docs
      - name: 'Upload as pages-artifact'
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'api-docs'
          name: api-docs
  deploy:
    runs-on: ubuntu-latest
    needs: generate
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 'Checkout (for repo metadata)'
        uses: actions/checkout@v4
      - name: 'Deploy to Pages'
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: api-docs
